# Generated by Django 4.0.3 on 2022-03-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='stad',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='nummer',
            field=models.CharField(default='+31 6', max_length=200),
        ),
    ]
