# Generated by Django 4.0.3 on 2022-03-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_city_shippingaddress_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='nummer',
            field=models.IntegerField(default='+31 6', max_length=200),
        ),
    ]
