# Generated by Django 4.0.3 on 2022-03-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_shippingaddress_nummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='nummer',
            field=models.IntegerField(default='+31 6'),
        ),
    ]
