# Generated by Django 4.0.3 on 2022-03-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_shippingaddress_nummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='nummer',
            field=models.CharField(default='+31 6', max_length=30),
        ),
    ]
