# Generated by Django 4.0.3 on 2022-04-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_image1_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
