# Generated by Django 4.0.3 on 2022-03-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_alter_geeksmodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='prijs',
            field=models.IntegerField(default=0),
        ),
    ]
